name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/marcello.cerruti/test"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "marcellocerruti"
        GITLAB_PASSWORD: "k9ZEExiqjxBejsiuHcW5" // Generate here: https://gitlab.com/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "27258425" 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
